//! Lightweight FHIR R5 validation.
//!
//! Provides format checks for the FHIR R5 primitive datatypes (the
//! regular-expression constraints from the specification, implemented without
//! an external regex dependency), and bridges validation results into an R5
//! `OperationOutcome`.
//!
//! The [`Validate`] trait and [`ValidationIssue`] type are shared by every FHIR
//! release and live in [`::fhir_core::validate`]; this module re-exports them so R5
//! code keeps using `fhir::r5::validate::Validate`. Recursive validation of
//! complex types and resources is generated by `#[derive(Validate)]`.
//!
//! # Examples
//!
//! ```
//! use fhir::r5::types::Id;
//! use fhir::r5::validate::Validate;
//!
//! assert!(Id("patient-1".to_string()).validate().is_empty());
//! assert!(!Id("bad id!".to_string()).validate().is_empty());
//! ```

use crate::r5::types;
use ::fhir_core::validate::{is_valid_code, is_valid_id, is_valid_uri_like};

pub use ::fhir_core::validate::{Validate, ValidationIssue};

impl From<ValidationIssue> for crate::r5::resources::operation_outcome::OperationOutcomeIssue {
    fn from(issue: ValidationIssue) -> Self {
        use crate::r5::coded::Coded;
        use crate::r5::codes::{IssueSeverity, IssueType};
        Self {
            severity: Coded::Known(IssueSeverity::Error),
            code: Coded::Known(IssueType::Invalid),
            diagnostics: Some(types::String(issue.message)),
            expression: vec![types::String(issue.path)],
            ..Default::default()
        }
    }
}

/// Bridge validation results into a FHIR `OperationOutcome` — each
/// [`ValidationIssue`] becomes an `issue` entry with `error` severity and an
/// `invalid` code, its message in `diagnostics` and its path in `expression`.
///
/// ```
/// use fhir::r5::resources::Patient;
/// use fhir::r5::resources::operation_outcome::OperationOutcome;
/// use fhir::r5::types::Uri;
/// use fhir::r5::validate::Validate;
///
/// let mut patient = Patient::default();
/// patient.implicit_rules = Some(Uri(" bad ".to_string()));
///
/// let outcome: OperationOutcome = patient.validate().into();
/// assert_eq!(outcome.issue.len(), 1);
/// assert_eq!(outcome.issue[0].expression[0].0, "implicit_rules.uri");
/// ```
impl From<Vec<ValidationIssue>> for crate::r5::resources::operation_outcome::OperationOutcome {
    fn from(issues: Vec<ValidationIssue>) -> Self {
        use crate::r5::coded::Coded;
        use crate::r5::codes::{IssueSeverity, IssueType};
        use crate::r5::resources::operation_outcome::{OperationOutcome, OperationOutcomeIssue};

        let mut items: Vec<OperationOutcomeIssue> = issues.into_iter().map(Into::into).collect();
        if items.is_empty() {
            // `OperationOutcome.issue` is 1..*; represent "no problems" as an
            // information-severity issue.
            items.push(OperationOutcomeIssue {
                severity: Coded::Known(IssueSeverity::Information),
                code: Coded::Known(IssueType::Informational),
                diagnostics: Some(types::String("No issues detected.".to_string())),
                ..Default::default()
            });
        }
        OperationOutcome {
            issue: ::vec1::Vec1::try_from_vec(items).expect("non-empty"),
            id: None,
            meta: None,
            implicit_rules: None,
            implicit_rules_ext: None,
            language: None,
            language_ext: None,
            text: None,
            contained: Vec::new(),
            extension: Vec::new(),
            modifier_extension: Vec::new(),
        }
    }
}

impl Validate for types::Code {
    fn validate(&self) -> Vec<ValidationIssue> {
        if is_valid_code(&self.0) {
            vec![]
        } else {
            vec![ValidationIssue::new(
                "code",
                format!("invalid FHIR code: {:?}", self.0),
            )]
        }
    }
}

impl Validate for types::Id {
    fn validate(&self) -> Vec<ValidationIssue> {
        if is_valid_id(&self.0) {
            vec![]
        } else {
            vec![ValidationIssue::new(
                "id",
                format!("invalid FHIR id: {:?}", self.0),
            )]
        }
    }
}

impl Validate for types::Oid {
    fn validate(&self) -> Vec<ValidationIssue> {
        if self.0.starts_with("urn:oid:") {
            vec![]
        } else {
            vec![ValidationIssue::new(
                "oid",
                "FHIR oid must start with `urn:oid:`",
            )]
        }
    }
}

impl Validate for types::Uuid {
    fn validate(&self) -> Vec<ValidationIssue> {
        if self.0.starts_with("urn:uuid:") {
            vec![]
        } else {
            vec![ValidationIssue::new(
                "uuid",
                "FHIR uuid must start with `urn:uuid:`",
            )]
        }
    }
}

impl Validate for types::Uri {
    fn validate(&self) -> Vec<ValidationIssue> {
        if is_valid_uri_like(&self.0) {
            vec![]
        } else {
            vec![ValidationIssue::new(
                "uri",
                "FHIR uri must be non-empty and not surrounded by whitespace",
            )]
        }
    }
}

impl Validate for types::Canonical {
    fn validate(&self) -> Vec<ValidationIssue> {
        if is_valid_uri_like(&self.0) {
            vec![]
        } else {
            vec![ValidationIssue::new(
                "canonical",
                "must be non-empty and not surrounded by whitespace",
            )]
        }
    }
}

impl Validate for types::Url {
    fn validate(&self) -> Vec<ValidationIssue> {
        if is_valid_uri_like(&self.0) {
            vec![]
        } else {
            vec![ValidationIssue::new(
                "url",
                "must be non-empty and not surrounded by whitespace",
            )]
        }
    }
}

/// Primitives whose Rust representation already guarantees validity, so there
/// is no further structural constraint to check here.
///
/// `Decimal` is deliberately absent: it is one shared type at the crate root
/// (`::fhir_core::decimal`) rather than one per release, so it implements
/// `Validate` there. Listing it here too would be a conflicting impl the
/// moment two releases are compiled together.
macro_rules! always_valid {
    ($($t:ty),* $(,)?) => {
        $(impl Validate for $t {
            fn validate(&self) -> Vec<ValidationIssue> { Vec::new() }
        })*
    };
}

always_valid!(
    types::Base64Binary,
    types::Boolean,
    types::Date,
    types::DateTime,
    types::Instant,
    types::Integer,
    types::Integer64,
    types::Markdown,
    types::PositiveInt,
    types::String,
    types::Time,
    types::UnsignedInt,
    types::Xhtml,
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn code_ok() {
        assert!(types::Code("final".to_string()).is_valid());
        assert!(types::Code("entered in error".to_string()).is_valid());
    }

    #[test]
    fn code_bad() {
        assert!(!types::Code(" leading".to_string()).is_valid());
        assert!(!types::Code("double  space".to_string()).is_valid());
        assert!(!types::Code(String::new()).is_valid());
    }

    #[test]
    fn id_ok_and_bad() {
        assert!(types::Id("abc-123.4".to_string()).is_valid());
        assert!(!types::Id("bad id!".to_string()).is_valid());
        assert!(!types::Id("x".repeat(65)).is_valid());
    }

    #[test]
    fn option_and_vec() {
        let good: Option<types::Code> = Some(types::Code("ok".to_string()));
        assert!(good.validate().is_empty());
        let bad = vec![types::Id("ok".to_string()), types::Id("no!".to_string())];
        assert_eq!(bad.validate().len(), 1);
    }

    // T13: a required binding rejects a code outside the value set.
    #[test]
    fn required_binding_flags_unknown_code() {
        use crate::r5::coded::Coded;
        use crate::r5::codes::AdministrativeGender;
        use crate::r5::resources::Patient;

        let mut patient = Patient {
            gender: Some(Coded::Known(AdministrativeGender::Male)),
            ..Default::default()
        };
        assert!(patient.validate().is_empty());

        patient.gender = Some(Coded::Unknown("robot".to_string()));
        let issues = patient.validate();
        assert_eq!(issues.len(), 1);
        assert_eq!(issues[0].path, "gender.code");
    }

    // T14: ext-1 — an Extension must have a value XOR nested extensions.
    #[test]
    fn invariant_ext_1() {
        use crate::r5::choice::Primitive;
        use crate::r5::types::extension::{Extension, ExtensionValue};
        use crate::r5::types::{Boolean, String as FhirString};

        let url = || FhirString("http://example.org/x".to_string());

        // Neither value nor extension -> violates ext-1.
        let neither = Extension {
            url: url(),
            ..Default::default()
        };
        assert!(
            neither
                .validate()
                .iter()
                .any(|i| i.message.contains("ext-1"))
        );

        // Exactly a value -> ok.
        let value_only = Extension {
            url: url(),
            value: Some(ExtensionValue::Boolean(Primitive::new(Boolean(true)))),
            ..Default::default()
        };
        assert!(
            !value_only
                .validate()
                .iter()
                .any(|i| i.message.contains("ext-1"))
        );

        // Both value and a nested extension -> violates ext-1.
        let both = Extension {
            url: url(),
            value: Some(ExtensionValue::Boolean(Primitive::new(Boolean(true)))),
            extension: vec![value_only.clone()],
            ..Default::default()
        };
        assert!(both.validate().iter().any(|i| i.message.contains("ext-1")));
    }

    // T14: dom-2 — a contained resource must not itself contain resources.
    #[test]
    fn invariant_dom_2() {
        use crate::r5::resources::Patient;

        let patient = Patient {
            // The fixture must be a *valid* Observation now that `contained`
            // is typed (T47) — the raw-JSON version could hold one missing
            // its required `status` and `code`; the typed one cannot.
            contained: vec![serde_json::from_value(serde_json::json!({
                "resourceType": "Observation",
                "id": "o1",
                "status": "final",
                "code": { "text": "x" },
                "contained": [{ "resourceType": "Patient", "id": "nested" }]
            }))
            .expect("a valid contained resource")],
            ..Default::default()
        };
        assert!(
            patient
                .validate()
                .iter()
                .any(|i| i.message.contains("dom-2"))
        );
    }

    // ele-1 — an element must carry a value or a child that is not its id.
    #[test]
    fn invariant_ele_1() {
        let flagged = |i: &[crate::validate::ValidationIssue]| {
            i.iter().any(|x| x.message.contains("ele-1"))
        };

        // Nothing at all.
        assert!(flagged(&types::Coding::default().validate()));

        // One real child is enough.
        let coded = types::Coding {
            code: Some(types::Code("final".to_string())),
            ..Default::default()
        };
        assert!(!flagged(&coded.validate()));

        // `id` alone does NOT count: the rule is
        // `children().count() > id.count()`, so an element whose only child is
        // its id fails it.
        let id_only = types::Element {
            id: Some(types::String("x".to_string())),
            ..Default::default()
        };
        assert!(flagged(&id_only.validate()), "id alone is not a child for ele-1");

        // An extension is a child.
        let with_ext = types::Element {
            extension: vec![types::Extension {
                url: types::String("http://example.org/x".to_string()),
                ..Default::default()
            }],
            ..Default::default()
        };
        assert!(!flagged(&with_ext.validate()));

        // A resource root is NOT an Element — `Resource` descends from `Base` —
        // and no resource root carries ele-1 in the specification. An empty
        // Patient is unhelpful, but it is not an ele-1 violation.
        assert!(
            !flagged(&crate::r5::resources::Patient::default().validate()),
            "ele-1 is not stated on any resource root"
        );
    }

    // att-1 — bytes with no media type cannot be interpreted by a receiver.
    #[test]
    fn invariant_att_1() {
        let flagged = |a: &types::Attachment| a.validate().iter().any(|i| i.message.contains("att-1"));

        let data_only = types::Attachment {
            data: Some(types::Base64Binary("aGk=".to_string())),
            ..Default::default()
        };
        assert!(flagged(&data_only), "data without contentType violates att-1");

        let with_type = types::Attachment {
            data: Some(types::Base64Binary("aGk=".to_string())),
            content_type: Some(types::Code("text/plain".to_string())),
            ..Default::default()
        };
        assert!(!flagged(&with_type));

        // No data at all: the rule does not apply.
        let neither = types::Attachment::default();
        assert!(!flagged(&neither));
    }

    // qty-3 — a unit code means nothing without the system that defines it.
    #[test]
    fn invariant_qty_3() {
        let flagged = |q: &types::Quantity| q.validate().iter().any(|i| i.message.contains("qty-3"));

        let code_only = types::Quantity {
            code: Some(types::Code("mg".to_string())),
            ..Default::default()
        };
        assert!(flagged(&code_only));

        let both = types::Quantity {
            code: Some(types::Code("mg".to_string())),
            system: Some(types::Uri("http://unitsofmeasure.org".to_string())),
            ..Default::default()
        };
        assert!(!flagged(&both));

        // The specializations state the same rule, and get the same check.
        let age = types::Age {
            code: Some(types::Code("a".to_string())),
            ..Default::default()
        };
        assert!(age.validate().iter().any(|i| i.message.contains("qty-3")));

        // A Coding also has `code` and `system`, and must NOT be caught by it.
        let coding = types::Coding {
            code: Some(types::Code("final".to_string())),
            ..Default::default()
        };
        assert!(!coding.validate().iter().any(|i| i.message.contains("qty-3")));
    }

    // drq-1 — exactly one of path and searchParam, so both and neither are
    // equally wrong.
    #[test]
    fn invariant_drq_1() {
        use crate::r5::types::data_requirement::DataRequirementCodeFilter;

        let flagged =
            |f: &DataRequirementCodeFilter| f.validate().iter().any(|i| i.message.contains("drq-1"));

        assert!(flagged(&DataRequirementCodeFilter::default()), "neither is a violation");

        let both = DataRequirementCodeFilter {
            path: Some(types::String("Observation.code".to_string())),
            search_param: Some(types::String("code".to_string())),
            ..Default::default()
        };
        assert!(flagged(&both), "both is a violation too");

        let path_only = DataRequirementCodeFilter {
            path: Some(types::String("Observation.code".to_string())),
            ..Default::default()
        };
        assert!(!flagged(&path_only));
    }

    // inv-1 — parts, or exactly one of a value and a resource; never a mixture.
    #[test]
    fn invariant_inv_1() {
        use crate::r5::choice::Primitive;
        use crate::r5::resources::parameters::{ParametersParameter, ParametersParameterValue};

        let flagged =
            |p: &ParametersParameter| p.validate().iter().any(|i| i.message.contains("inv-1"));

        let name = || types::String("x".to_string());
        let value = || ParametersParameterValue::Boolean(Primitive::new(types::Boolean(true)));

        // Nothing at all.
        assert!(flagged(&ParametersParameter { name: name(), ..Default::default() }));

        // Exactly a value.
        let value_only = ParametersParameter {
            name: name(),
            value: Some(value()),
            ..Default::default()
        };
        assert!(!flagged(&value_only));

        // Parts alone.
        let parts = ParametersParameter {
            name: name(),
            part: vec![value_only.clone()],
            ..Default::default()
        };
        assert!(!flagged(&parts));

        // Parts and a value together.
        let mixed = ParametersParameter {
            name: name(),
            value: Some(value()),
            part: vec![value_only],
            ..Default::default()
        };
        assert!(flagged(&mixed));
    }

    // T13: 1..* cardinality is now enforced at the type level — a `1..*` field is
    // a non-empty `Vec1<T>`, so an empty required list is unrepresentable.
    #[test]
    fn one_or_more_is_a_non_empty_vec1() {
        use crate::r5::resources::appointment::AppointmentParticipant;
        let empty: Vec<AppointmentParticipant> = Vec::new();
        assert!(::vec1::Vec1::try_from_vec(empty).is_err());
        assert!(::vec1::Vec1::try_from_vec(vec![AppointmentParticipant::default()]).is_ok());
    }

    #[test]
    fn derived_validate_recurses_with_dotted_path() {
        // The `#[derive(Validate)]` on Coding recurses into its `code` field,
        // whose primitive validator flags the double space.
        let coding = types::Coding {
            code: Some(types::Code("bad  code".to_string())),
            ..Default::default()
        };
        let issues = coding.validate();
        assert_eq!(issues.len(), 1, "{issues:?}");
        assert_eq!(issues[0].path, "code.code");

        // A well-formed Coding validates clean.
        let ok = types::Coding {
            code: Some(types::Code("final".to_string())),
            ..Default::default()
        };
        assert!(ok.validate().is_empty());
    }
}
