//! The relational map: a compact, serializable description of how one FHIR
//! version's resources shred into relational tables. Generated by
//! `fhir-mssql-gen` from the official StructureDefinitions; consumed by the
//! generic shred/reconstruct engine and the DDL emitter.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// The complete relational map for one FHIR version.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelMap {
    /// FHIR publication version, e.g. "5.0.0".
    pub fhir_version: String,
    /// PostgreSQL schema name, e.g. "r5".
    pub schema: String,
    pub resources: BTreeMap<String, ResourceMap>,
}

/// One resource type's tables and element tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceMap {
    /// Resource type name, e.g. "Patient".
    pub name: String,
    /// Table 0 is the base table; the fixed-shape system tables (ext, deep,
    /// contained, history) are also in this list so DDL and stores can
    /// enumerate everything.
    pub tables: Vec<Table>,
    /// Node arena. Nodes reference each other by index, which permits the
    /// cycles that recursive elements (contentReference) require.
    pub nodes: Vec<Node>,
    /// Root node (the resource's own elements). Always present in practice;
    /// index into `nodes`.
    pub root: u32,
    /// Compiled search parameters, generated from the version's
    /// SearchParameter definitions.
    #[serde(default)]
    pub search: Vec<SearchDef>,
}

/// One search parameter, compiled against this resource's tables.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchDef {
    /// Parameter code as used in query strings ("family", "code", …).
    pub code: String,
    pub ty: SearchTy,
    /// Places this parameter matches; a value matches when ANY target does.
    /// Empty means the parameter is known but not yet compilable — servers
    /// report it unsupported instead of lying.
    pub targets: Vec<SearchTarget>,
    /// Why targets are empty, for the generated support matrix.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SearchTy {
    Number,
    Date,
    String,
    Token,
    Reference,
    Composite,
    Quantity,
    Uri,
    Special,
}

/// One concrete place a search parameter matches: a table plus the columns
/// the predicate tests.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchTarget {
    /// Index into `ResourceMap.tables`; 0 = base table (no join needed).
    pub table: u32,
    pub kind: TargetKind,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TargetKind {
    /// Case- and accent-insensitive prefix/contains match on a text column.
    Str {
        col: String,
        /// Companion folded column (P6.6). `:exact` compares `col`; every
        /// other modifier compares `norm`. `None` only for maps generated
        /// before folding existed.
        #[serde(default)]
        norm: Option<String>,
    },
    /// system|code semantics. `system` is None for bare code/boolean
    /// primitives.
    Token {
        system: Option<String>,
        code: String,
    },
    /// Temporal comparison against the derived sort column; `hi` is the end
    /// column for Period elements.
    Date {
        lo: String,
        hi: Option<String>,
    },
    Number {
        col: String,
    },
    Quantity {
        value: String,
        system: Option<String>,
        code: Option<String>,
    },
    Reference {
        c_type: String,
        c_id: String,
        c_url: String,
    },
    Uri {
        col: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TableKind {
    /// One row per resource: `id text PRIMARY KEY, version_id bigint,
    /// last_updated timestamptz`, plus data columns.
    Base,
    /// One row per instance of a repeating (or force-split) element:
    /// `rid text, ords smallint[]`, PK (rid, ords), plus data columns.
    Elem,
    /// Extension leaves: `rid, path, ords, modifier, ext_ord, url, leaf,
    /// v_kind, v_text, v_num, v_bool`.
    Ext,
    /// Type-recursion spill leaves: `rid, path, ords, leaf, v_kind, v_text,
    /// v_num, v_bool`.
    Deep,
    /// Contained resources: `rid, ord, resource jsonb`.
    Contained,
    /// Version history: `id, version_id, last_updated, op, resource jsonb`.
    History,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Table {
    pub name: String,
    pub kind: TableKind,
    /// FHIR element path this table stores ("Patient.name.given");
    /// empty for base and system tables.
    pub path: String,
    /// Data columns. Empty for the fixed-shape system tables.
    pub cols: Vec<Column>,
    /// `(source, folded)` column-name pairs (P6.6). The shredder fills each
    /// `folded` column from the `source` value it just wrote, so the write
    /// path and the query path share one definition of string equality.
    #[serde(default)]
    pub norm_cols: Vec<(String, String)>,
    /// Search adjuncts for columns this dialect cannot index or compare as
    /// bound (`U1`, `U1a`). Present only where `ddl::TEXT_ADJUNCTS` is set, per
    /// `U9`, so the engines that need neither pay for neither.
    #[serde(default)]
    pub adjunct_cols: Vec<Adjuncts>,
}

/// Which adjuncts a column has, and under what names.
///
/// `U2b` requires the map to record **which** exist rather than assume a pair.
/// `U2` reads as though both always do, and for a `string` target both do —
/// prefix and `:exact` are both performed. `U2a` qualifies that: a column a
/// search only ever compares for equality has no use for a bounded adjunct, and
/// `U13` forbids one outright over opaque bytes, where it would enable ordering
/// by the first *n* bytes of an encoded payload rather than any FHIR search.
///
/// A query builder MUST consult these rather than assume: emitting a predicate
/// against an adjunct that was never generated fails only for the search shapes
/// nobody exercised, which is the worst way to find out.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Adjuncts {
    /// The column these are derived from.
    pub source: String,
    /// `<col>_idx` — bounded, folded, binary collation. Serves prefix, range
    /// and ordering. `None` when the search never performs those.
    #[serde(default)]
    pub bounded: Option<String>,
    /// `<col>_h` — SHA-256 of the whole value (`U4a`). Serves equality,
    /// `:exact` and token match. `None` when the search never compares for
    /// equality.
    #[serde(default)]
    pub digest: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Column {
    pub name: String,
    pub ty: ColTy,
    /// FHIR element path this column stores, for documentation and search
    /// compilation ("Patient.birthDate", "Observation.value[x]:Quantity.value").
    pub path: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ColTy {
    Bool,
    Int,
    BigInt,
    Numeric,
    Text,
    /// Derived search-fold column (P6.6). `COLLATE "C"` so that ordering is by
    /// Unicode codepoint, which is what lets a prefix search run as a plain
    /// btree range scan rather than a pattern match the planner has to
    /// recognise. Never reconstructed into a resource.
    TextC,
    /// Derived **bounded** adjunct for an unbounded text column (`U1`), in the
    /// folded form (`U5`) and a binary collation, so a prefix or range search
    /// can use an index on an engine that cannot index the source type. The
    /// bound *n* is the dialect's to choose and record (`U10`); the map only
    /// says the adjunct exists. Never reconstructed into a resource (`U3`).
    TextIdx,
    /// Derived **checksum** adjunct for an unbounded text column (`U1`): a
    /// fixed-width digest of the *whole* value, computed in Rust over the
    /// canonical bytes (`U4`), never by a SQL function. Serves equality where
    /// the source type cannot be compared. A match on this column is an access
    /// path, never an answer — `U6` requires confirming against the source.
    /// Never reconstructed into a resource (`U3`).
    Digest,
    /// Derived sort column for a FHIR date.
    Date,
    /// Derived sort column for a FHIR dateTime/instant.
    Timestamptz,
    Jsonb,
}

/// One object context: the elements of a resource root, backbone element, or
/// complex datatype, flattened into the current table row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Node {
    pub elems: Vec<Elem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Elem {
    /// JSON property name ("birthDate"; for a choice variant, the full name
    /// "valueBoolean"; for a choice element itself, the base name "value").
    pub json: String,
    /// FHIR element path, for error messages and documentation.
    pub path: String,
    /// True when max cardinality exceeds 1 (JSON array).
    pub repeats: bool,
    /// When Some, instances of this element get their own row in the given
    /// table (index into `ResourceMap.tables`): every repeating element, and
    /// non-repeating elements force-split to respect PostgreSQL's column
    /// limit. The row's `ords` is the parent's ords plus the 1-based array
    /// index (or 1 when the element does not repeat).
    pub table: Option<u32>,
    /// Lane sign for cyclic contentReference elements. When two elements
    /// recurse into the same table (QuestionnaireResponse: `item.item` and
    /// `item.answer.item` both target #QuestionnaireResponse.item), their
    /// ordinal paths would collide; the second referrer pushes negated
    /// ordinals so every path stays unambiguous.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub neg_lane: bool,
    pub kind: ElemKind,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ElemKind {
    Prim(PrimCol),
    /// The `Reference.reference` string, split into parsed columns.
    RefStr(RefCols),
    /// Complex datatype or backbone element: node index into the arena.
    /// Cyclic contentReference elements point back at an ancestor node and
    /// share its table.
    Group(u32),
    /// Choice element; each variant is a complete Elem whose `json` is the
    /// full variant property name.
    Choice(Vec<Elem>),
    /// Type-recursion cut: the whole subtree spills to the Deep table as
    /// leaf rows.
    Spill,
    /// An inline resource (e.g. Bundle.entry.resource) stored whole in a
    /// jsonb column.
    ResourceValue(String),
    /// DomainResource.contained, stored in the Contained table.
    Contained,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrimCol {
    pub col: String,
    /// Derived sort column for temporal primitives.
    pub sort: Option<String>,
    pub prim: Prim,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RefCols {
    /// Column holding the target resource type of a relative reference.
    pub c_type: String,
    /// Column holding the target id of a relative reference.
    pub c_id: String,
    /// Column holding any other reference verbatim (absolute URL, urn:,
    /// fragment, version-specific).
    pub c_url: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Prim {
    /// JSON bool → boolean.
    Bool,
    /// integer/unsignedInt/positiveInt: JSON number → integer.
    Int,
    /// R5 integer64: JSON string → bigint.
    Int64,
    /// JSON number → numeric, lexical form preserved.
    Decimal,
    /// JSON string, possibly partial ("2026-07") → text + date sort.
    Date,
    /// JSON string → text + timestamptz sort.
    DateTime,
    /// JSON string, always fully specified → text + timestamptz sort.
    Instant,
    /// JSON string → text (kept lexical for fractional-second fidelity).
    Time,
    /// Everything else stringly: string/code/id/uri/url/canonical/oid/uuid/
    /// markdown/xhtml/base64Binary → text.
    Str,
}

impl Prim {
    pub fn col_ty(self) -> ColTy {
        match self {
            Prim::Bool => ColTy::Bool,
            Prim::Int => ColTy::Int,
            Prim::Int64 => ColTy::BigInt,
            Prim::Decimal => ColTy::Numeric,
            Prim::Date | Prim::DateTime | Prim::Instant | Prim::Time | Prim::Str => ColTy::Text,
        }
    }

    pub fn sort_ty(self) -> Option<ColTy> {
        match self {
            Prim::Date => Some(ColTy::Date),
            Prim::DateTime | Prim::Instant => Some(ColTy::Timestamptz),
            _ => None,
        }
    }
}

/// Errors from [`RelMap::bundled`].
#[derive(Debug)]
pub enum BundledError {
    /// The version is real, but this crate was built without its feature.
    NotCompiled(&'static str),
    /// Not a FHIR version this port ships a map for.
    UnknownVersion(String),
    /// The embedded bytes did not decode — a build-time corruption, not a
    /// caller error.
    Decode(std::io::Error),
}

impl std::fmt::Display for BundledError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotCompiled(v) => write!(
                f,
                "the {v} map is not compiled in; enable the \"{v}\" feature of this crate"
            ),
            Self::UnknownVersion(v) => write!(f, "no bundled map for FHIR version {v:?}"),
            Self::Decode(e) => write!(f, "bundled map failed to decode: {e}"),
        }
    }
}
impl std::error::Error for BundledError {}

// One pair per version rather than `#[cfg]` inside a single body: with every
// version disabled, a shared `let bytes = match { ... }` is dead and the
// compiler rightly warns about it. This shape compiles clean at every
// combination of the three features, including none.

#[cfg(feature = "r3")]
fn bundled_r3() -> Result<RelMap, BundledError> {
    // Bound to a const so the line width does not depend on the crate name:
    // `fhir-postgresql` is four characters longer than `fhir-sqlite`, which was
    // enough to make rustfmt wrap this call differently there and break X15.1's
    // byte-identity for a purely cosmetic reason.
    const GZ: &[u8] = include_bytes!("../assets/fhir-mssql-relmap-r3.json.gz");
    RelMap::from_gz_bytes(GZ).map_err(BundledError::Decode)
}
#[cfg(not(feature = "r3"))]
fn bundled_r3() -> Result<RelMap, BundledError> {
    Err(BundledError::NotCompiled("r3"))
}

#[cfg(feature = "r4")]
fn bundled_r4() -> Result<RelMap, BundledError> {
    // Bound to a const so the line width does not depend on the crate name:
    // `fhir-postgresql` is four characters longer than `fhir-sqlite`, which was
    // enough to make rustfmt wrap this call differently there and break X15.1's
    // byte-identity for a purely cosmetic reason.
    const GZ: &[u8] = include_bytes!("../assets/fhir-mssql-relmap-r4.json.gz");
    RelMap::from_gz_bytes(GZ).map_err(BundledError::Decode)
}
#[cfg(not(feature = "r4"))]
fn bundled_r4() -> Result<RelMap, BundledError> {
    Err(BundledError::NotCompiled("r4"))
}

#[cfg(feature = "r5")]
fn bundled_r5() -> Result<RelMap, BundledError> {
    // Bound to a const so the line width does not depend on the crate name:
    // `fhir-postgresql` is four characters longer than `fhir-sqlite`, which was
    // enough to make rustfmt wrap this call differently there and break X15.1's
    // byte-identity for a purely cosmetic reason.
    const GZ: &[u8] = include_bytes!("../assets/fhir-mssql-relmap-r5.json.gz");
    RelMap::from_gz_bytes(GZ).map_err(BundledError::Decode)
}
#[cfg(not(feature = "r5"))]
fn bundled_r5() -> Result<RelMap, BundledError> {
    Err(BundledError::NotCompiled("r5"))
}

impl RelMap {
    pub fn to_gz_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        use flate2::{Compression, write::GzEncoder};
        use std::io::Write as _;
        let json = serde_json::to_vec(self)?;
        let mut enc = GzEncoder::new(Vec::new(), Compression::default());
        enc.write_all(&json).expect("gz write");
        Ok(enc.finish().expect("gz finish"))
    }

    /// The bundled relational map for one FHIR version, compiled into the binary.
    ///
    /// The maps are generated artifacts committed under this crate's `assets/`
    /// (`G2.1`) and embedded with `include_bytes!`, so a consumer who runs
    /// `cargo add` gets a working engine rather than one with nothing to walk
    /// (**F-33**). Before this there was no constructor except
    /// [`RelMap::from_gz_bytes`] over a file the package did not contain.
    ///
    /// **Per-version features**, matching the shape the model family already
    /// uses for its release crates: `r3`, `r4`, `r5`, with `r5` on by default.
    ///
    /// A caveat worth stating plainly: the features gate **compilation**, not
    /// the download. A `.crate` archive is static, so all three maps travel
    /// with it (~2.5 MB) however few you enable. Making the download opt-in
    /// too would take separate data crates, which is a different trade.
    ///
    /// # Errors
    /// [`BundledError::NotCompiled`] when the version's feature is off,
    /// [`BundledError::UnknownVersion`] for anything this port does not ship,
    /// and [`BundledError::Decode`] if the embedded bytes are corrupt.
    pub fn bundled(version: &str) -> Result<Self, BundledError> {
        match version {
            "r3" => bundled_r3(),
            "r4" => bundled_r4(),
            "r5" => bundled_r5(),
            other => Err(BundledError::UnknownVersion(other.to_string())),
        }
    }

    /// Which versions this build actually carries.
    #[must_use]
    pub fn bundled_versions() -> &'static [&'static str] {
        &[
            #[cfg(feature = "r3")]
            "r3",
            #[cfg(feature = "r4")]
            "r4",
            #[cfg(feature = "r5")]
            "r5",
        ]
    }

    pub fn from_gz_bytes(bytes: &[u8]) -> Result<Self, std::io::Error> {
        use flate2::read::GzDecoder;
        let dec = GzDecoder::new(bytes);
        serde_json::from_reader(dec).map_err(std::io::Error::other)
    }
}

impl ResourceMap {
    pub fn node(&self, id: u32) -> &Node {
        &self.nodes[id as usize]
    }

    pub fn table(&self, id: u32) -> &Table {
        &self.tables[id as usize]
    }

    pub fn base_table(&self) -> &Table {
        &self.tables[0]
    }

    pub fn find_table(&self, kind: TableKind) -> Option<(u32, &Table)> {
        self.tables
            .iter()
            .enumerate()
            .find(|(_, t)| t.kind == kind)
            .map(|(i, t)| (i as u32, t))
    }
}
