//! DDL emission — **Oracle**.
//!
//! # What was verified, and how
//!
//! The whole emitter, by installing what it produces on **Oracle AI Database
//! 26ai Free (23.26.2.0.0)**: the complete R5 schema, 158 resources, 9,636
//! statements, in one pass, with zero errors and zero invalid objects.
//!
//! Executing it is not a formality here — it is where the defects were.
//! Reading the code would not have found any of these:
//!
//! - `NUMBER(1) CHECK (VALUE IN (0,1))` from `col_sql` fails with `ORA-02438`,
//!   because a column check may not name another column. The constraint moved
//!   to `create_table`, which knows the column's name (`M14.23e`), and that is
//!   what earns `M14.8`.
//! - The append-only DELETE guard **failed open**. The MySQL original reads
//!   `COALESCE(@var, '') <> 'on'`; translated as `NVL(SYS_CONTEXT(…), '')` it
//!   is still NULL when unset, `NULL != 'x'` is NULL rather than TRUE, and the
//!   `ELSIF` never fires. An ordinary `DELETE` on history succeeded with no
//!   error at all. The sentinel is now `'unset'`.
//! - `search_indexes` reported 453 of R5's 1,947 targets unindexable, all of
//!   them reference pairs, which turned out to be a shared-core defect in the
//!   adjunct rules (**F-50**). Gaps are now 0.
//!
//! The engine facts underneath are measured too, not cited: the 4000-**byte**
//! `VARCHAR2` ceiling, the 128-byte identifier limit, that a `CLOB` can be
//! neither indexed (`ORA-02327`) nor `=` compared (`ORA-22848`) — the last two
//! being the premise of `U1`–`U10` — and that a `CLOB` cannot join a key at all
//! (`ORA-02329`), which is why `Ext`/`Deep` use a hash surrogate.
//!
//! # How this differs from the MySQL emitter it was forked from
//!
//! | | MySQL | Here |
//! | --- | --- | --- |
//! | Quoting | `` `x` `` | `"x"` — and required, since bare identifiers fold to upper case |
//! | Namespace | one schema | one **user** per version (`M14.5`), provisioned out of band (`M14.28`) |
//! | Idempotency | `IF NOT EXISTS` | a PL/SQL block swallowing `ORA-00955`/`-01408` only (`M14.31`) |
//! | Surrogate keys | `AUTO_INCREMENT` | `GENERATED BY DEFAULT AS IDENTITY` |
//! | Unindexable text | prefix index `col(255)` | the `U1` adjunct — `<col>_idx`, else `<col>_h` |
//! | `rid` lookup | inline `KEY` clause | its own `CREATE INDEX` (`M14.30`) |
//! | Append-only | two triggers + `SIGNAL` | one trigger, `raise_application_error` |
//! | Erasure flag | session variable | `CLIENT_INFO` (`M14.29`) |
//!
//! # What is still missing
//!
//! There is no store and no driver, so nothing has been *written* through this
//! schema by the port itself — only by hand, to prove the guards fire. `C0.9`
//! keeps this port at **Scaffold**: `C0.8` has four levels and `C0.9` wants the
//! claim justified by a test that runs. This was verified by hand, so the
//! honest level is unchanged and **Schema** is one live test away.

use std::fmt::Write as _;

use crate::model::{ColTy, RelMap, ResourceMap, Table, TableKind};

/// Oracle's `VARCHAR2` ceiling under `max_string_size = STANDARD`, **in bytes**.
///
/// Measured on 26ai, not read from a manual: `varchar2(4001 byte)` is refused
/// with `ORA-00910: specified length too long for its datatype` (`M14.23b`).
const MAX_VARCHAR2_BYTES: usize = 4000;

/// Worst-case bytes per character under `AL32UTF8`, which is this engine's
/// character set here (`M14.23d`).
const BYTES_PER_CHAR: usize = 4;

/// The largest `VARCHAR2` bound, **in characters**, that is safe for arbitrary
/// Unicode.
///
/// This is the correction `M14.23d` records. `VARCHAR2(4000 CHAR)` looks like
/// 4000 characters and is not: the `STANDARD` ceiling is a *byte* ceiling, so
/// the declaration is capped at 4000 bytes and holds as few as 1000 characters.
/// A genuine 3000-character value is refused with
/// `ORA-12899: value too large for column … (actual: 6000, maximum: 4000)`.
///
/// Anything a FHIR `string` might exceed therefore has to be `CLOB`, which is
/// why `U1`–`U10`'s adjuncts are load-bearing on this engine for far more
/// columns than `M14.6`'s table suggests.
const MAX_VARCHAR2_CHARS: usize = MAX_VARCHAR2_BYTES / BYTES_PER_CHAR;

// ---------------------------------------------------------------------------
// STILL MYSQL, below this line, in the functions this pass did not port.
//
// Oracle has no index-prefix syntax at all — `create index … (col(20))` is a
// MySQL/MariaDB feature. The two constants that described it, `MAX_KEY_BYTES`
// and `MAX_PREFIX_CHARS`, are **gone**: where MySQL indexes a prefix of an
// unbounded column, this port indexes the bounded adjunct instead (`U1`–`U10`),
// and where there is no adjunct it emits no index and reports the gap.
// ---------------------------------------------------------------------------

/// The character bound this port declares for every indexable text column —
/// `TextC` and `U1`'s `<col>_idx` — recorded here as `U10` requires.
///
/// 450 characters is 1800 bytes under `AL32UTF8`, comfortably inside the
/// measured ceiling.
const TEXTC_BOUND_CHARS: usize = 450;

/// The bound must fit the ceiling **in bytes**, checked at compile time rather
/// than left to a reviewer.
///
/// This is the trap `M14.23d` records: `VARCHAR2(n CHAR)` reads as characters
/// and is enforced as bytes, so a bound that looks safe can be refused with
/// `ORA-00910`. Raising `TEXTC_BOUND_CHARS` past 1000 stops the build here
/// instead of at someone's `CREATE TABLE`.
const _: () = assert!(TEXTC_BOUND_CHARS <= MAX_VARCHAR2_CHARS);
const _: () = assert!(TEXTC_BOUND_CHARS * BYTES_PER_CHAR <= MAX_VARCHAR2_BYTES);

/// The FHIR `id` type is `[A-Za-z0-9\-\.]{1,64}`, so 64 characters is an exact
/// bound rather than a guess. All of them are ASCII, so `64 CHAR` costs 256
/// bytes here and stays far inside the key limit.
///
/// `VARCHAR2` rather than `CHAR`: `CHAR` is blank-padded, under which
/// `'abc' = 'abc '`, and `M3.6b` forbids exactly that — it would widen `:exact`
/// and weaken key identity (`M14.10`).
const ID_COL: &str = "VARCHAR2(64 CHAR)";

/// Oracle type mapping for the map's column types (`M14.6`–`M14.12`).
///
/// Every binding below has been executed against Oracle AI Database 26ai Free
/// and reported back by `user_tab_columns` (`M14.23d`). None of it is inferred.
/// Does this dialect need the unbounded-string adjuncts (`U1`, `U9`)?
///
/// A `CLOB` can be neither indexed (`ORA-02327`) nor `=` compared
/// (`ORA-22848`) — both measured — which is the case that made that section
/// necessary and the reason both adjuncts are required rather than one.
///
/// The generator reads this to decide whether to put `<col>_idx` and `<col>_h`
/// in the map at all. `gen` is byte-identical across all six ports (`X15.1`);
/// this constant is in `ddl.rs`, which is the one file a dialect may own.
pub const TEXT_ADJUNCTS: bool = true;

/// Can this dialect **not** index or compare a column of this type as bound?
///
/// The second half of `U1a`'s trigger. The first — that a search reaches the
/// column — is the generator's to know; this is the dialect's, and only the two
/// together justify an adjunct.
///
/// A `CLOB` can be neither indexed (`ORA-02327`) nor `=` compared (`ORA-22848`) — both measured on 26ai.
///
/// Getting this wrong is not free in either direction. Return `true` too widely
/// and every boolean a token search touches grows a derived column nothing
/// reads; too narrowly and a search silently fails on the engine.
///
/// Every variant is listed rather than wildcarded, so adding a `ColTy` is a
/// compile error here and forces the decision instead of defaulting it.
pub fn needs_adjunct(ty: ColTy) -> bool {
    match ty {
        ColTy::Bool => false,
        ColTy::Int => false,
        ColTy::BigInt => false,
        ColTy::Numeric => false,
        ColTy::Text => true,
        ColTy::TextC => false,
        ColTy::TextIdx => false,
        ColTy::Digest => false,
        ColTy::Date => false,
        ColTy::Timestamptz => false,
        ColTy::Jsonb => true,
    }
}

pub fn col_sql(ty: ColTy) -> &'static str {
    match ty {
        // No native BOOLEAN: it arrived in 23ai and this port's floor is 12.2
        // (`M14.2`, `M14.4`). 26ai does have one — verified — but a schema
        // targeting 12.2 must not emit it however new the server happens to be
        // (`M14.23c`).
        //
        // The type alone, **without** the CHECK that makes it a boolean. That
        // is not an omission: a CHECK must name the column it constrains, and
        // this function is given only a type. Emitting
        // `NUMBER(1) CHECK (VALUE IN (0,1))` fails at `CREATE TABLE` with
        // `ORA-02438: Column check constraint cannot reference other columns` —
        // found by executing it, not by reading it (`M14.23e`).
        //
        // `create_table` owns the constraint, because it is the only caller
        // that knows the column name. Until it emits one, a `Bool` column here
        // is an unconstrained `NUMBER(1)` and this port MUST NOT claim `M14.8`.
        ColTy::Bool => "NUMBER(1)",
        ColTy::Int => "NUMBER(10)",
        ColTy::BigInt => "NUMBER(19)",
        // Not NUMBER: `M3.6a` and `M14.7`. Oracle's NUMBER is decimal and
        // high-precision, which makes it tempting, and it still normalizes —
        // `1.50` is stored and returned as `1.5`. `M3.6` requires the original
        // textual precision survive round-trip, so this binds to a character
        // type as it does on every engine but PostgreSQL. Range search is
        // served by a derived sort column, not by this one.
        ColTy::Numeric => "VARCHAR2(64 CHAR)",
        // `CLOB`, not `VARCHAR2`. A FHIR `string` has no length bound, and the
        // `VARCHAR2` ceiling is 4000 *bytes* — 1000 characters in the worst
        // case (`M14.23d`). Binding this to `VARCHAR2` would refuse long values
        // with `ORA-12899` rather than store them, which `R4.2` forbids.
        //
        // The cost is that this column can be neither indexed nor `=` compared,
        // which is precisely what `U1`–`U10` exist to answer: search reaches it
        // through `<col>_idx` and `<col>_h`, and `U6`'s confirming comparison
        // uses `DBMS_LOB.COMPARE` here.
        ColTy::Text => "CLOB",
        // Bounded, so it can be indexed, and `VARCHAR2` rather than `CHAR`
        // because `CHAR` is blank-padded and `M3.6b` forbids PAD SPACE
        // semantics (`M14.10`).
        ColTy::TextC => "VARCHAR2(450 CHAR)",
        // U1/U10: this port materializes both adjuncts. The bound is 450
        // characters — 1800 bytes under AL32UTF8, inside the 4000-byte ceiling.
        ColTy::TextIdx => "VARCHAR2(450 CHAR)",
        // U4a: SHA-256's 32 raw bytes. `RAW`, not `BLOB` — a BLOB would
        // reintroduce the very problem the checksum exists to solve, since
        // Oracle will not `=` compare a LOB.
        ColTy::Digest => "RAW(32)",
        // Oracle's DATE carries a time component; the value is a normalized
        // sort image written in Rust, so that is harmless here.
        ColTy::Date => "DATE",
        // TIMESTAMP(6) without a time zone (`M14.11`). Every value is
        // normalized to UTC in Rust before binding, so an offset column would
        // store a zero offset and invite the belief that local times are
        // preserved.
        ColTy::Timestamptz => "TIMESTAMP(6)",
        // `CLOB`, never Oracle's JSON type (`M3.6c`, `M14.12`). JSON
        // re-normalizes what it is given, so the bytes read back would not be
        // the bytes the hash chain signed and every chain would fail
        // verification.
        ColTy::Jsonb => "CLOB",
    }
}

/// Wrap a statement so that re-running it is not an error (`M14.31`).
///
/// Oracle gained `CREATE TABLE IF NOT EXISTS` in 23ai; this port's floor is
/// 12.2 (`M14.2`), so the idiom is a PL/SQL block that swallows exactly the
/// "name is already used" codes and re-raises everything else. Swallowing
/// `OTHERS` unconditionally would turn a genuine syntax error into a silent
/// success, which is the failure this whole port is being audited for.
///
///   `ORA-00955` name is already used by an existing object
///   `ORA-01408` such column list already indexed
///
/// `q'{...}'` avoids doubling the single quotes inside the statement. No DDL
/// emitted here contains `}'`, which is the only sequence that would end the
/// literal early.
fn idempotent(stmt: &str) -> String {
    debug_assert!(
        !stmt.contains("}'"),
        "q'{{...}}' literal would terminate early: {stmt}"
    );
    format!(
        "BEGIN\n  EXECUTE IMMEDIATE q'{{{stmt}}}';\n\
         EXCEPTION WHEN OTHERS THEN\n  \
         IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;\nEND;"
    )
}

/// All statements to install one version's schema, in application order.
pub fn ddl(map: &RelMap) -> Vec<String> {
    ddl_in(map, &map.schema)
}

/// The same statements, targeting an explicit schema name.
///
/// **No `CREATE USER` (`M14.28`).** `M14.5` binds a version namespace to an
/// Oracle *user*, and the obvious reading is that `init` should create it. This
/// does not, for two reasons. A `CREATE USER` before 18c must carry a password,
/// and a password embedded in generated DDL ends up in logs, in `V$SQL`, and in
/// whatever the caller prints — `NO AUTHENTICATION` would avoid that but
/// arrived in 18c, above this port's 12.2 floor (`M14.2`). And provisioning
/// three accounts with quotas and grants is a deployment act with site-specific
/// policy attached, not a schema detail.
///
/// So the three users are a **prerequisite**, documented in the annex and the
/// README rather than discovered: every statement below qualifies its object
/// with the schema name and assumes the account exists and the caller can write
/// to it.
///
/// `key` is `VARCHAR2(191 CHAR)` for no Oracle reason — it is what the MySQL
/// original chose to fit a `utf8mb4` index — but changing it would put the two
/// ports' metadata tables out of step for nothing, so it stands (`M14.28a`).
pub fn ddl_in(map: &RelMap, schema: &str) -> Vec<String> {
    let mut out = Vec::new();
    let s = schema;
    out.push(idempotent(&format!(
        "CREATE TABLE \"{s}\".\"fhir_oracle_meta\" (\
         \"key\" VARCHAR2(191 CHAR) NOT NULL PRIMARY KEY, \
         \"value\" CLOB NOT NULL)"
    )));
    out.extend(schema_wide_objects(s));
    for rm in map.resources.values() {
        for t in &rm.tables {
            out.push(create_table(s, rm, t));
            // Oracle has no inline index inside CREATE TABLE, so the `rid`
            // lookup the Ext/Deep read path needs is its own statement
            // (`M14.30`). On MySQL it is a `KEY` clause in the table body.
            if matches!(t.kind, TableKind::Ext | TableKind::Deep) {
                out.push(format!(
                    "CREATE INDEX \"{s}\".\"{}\" ON \"{s}\".\"{}\" (\"rid\")",
                    rid_index_name(&t.name),
                    t.name
                ));
            }
            if t.kind == TableKind::History {
                out.extend(append_only_triggers(s, &t.name));
            }
        }
        out.extend(search_indexes(s, rm));
    }
    out
}

/// Objects that exist once per schema rather than once per resource, written
/// idempotently so that `init` and `init --upgrade` can both apply them.
///
/// The per-resource table diff in the store cannot see these — they are not
/// in the relational map — so an upgrade applies them explicitly.
#[must_use]
pub fn schema_wide_objects(s: &str) -> Vec<String> {
    let mut out = vec![access_log_table(s), countersign_table(s)];
    out.extend(access_log_indexes(s));
    out
}

/// `ALTER TABLE … ADD COLUMN` for a history table's audit envelope, so an
/// installed schema gains M3.15/M3.16 without a rewrite. Purely additive:
/// existing rows get `actor = 'unauthenticated'` and a null chain, which
/// `verify-audit` reports as "chain starts here", not as a break.
///
/// Oracle has no `ADD COLUMN IF NOT EXISTS`, so these are **not** idempotent:
/// re-adding an existing column is `ORA-01430`. The caller MUST diff against
/// `all_tab_columns` first and apply only what is missing. (Note the keyword:
/// Oracle spells it `ADD`, not `ADD COLUMN`.)
#[must_use]
pub fn history_audit_columns(schema: &str, table: &str) -> Vec<String> {
    audit_envelope_columns()
        .iter()
        .map(|(name, ty)| format!("ALTER TABLE \"{schema}\".\"{table}\" ADD (\"{name}\" {ty})"))
        .collect()
}

/// The audit envelope, defined once so `create_table` and the upgrade path
/// cannot disagree about it.
///
/// `actor` carries no `DEFAULT`. Oracle would accept one on a `CLOB`, unlike
/// MySQL, but the store supplies `'unauthenticated'` explicitly on every engine
/// and a default here would only mask a store that forgot to. An upgraded
/// table's existing rows are therefore backfilled, not defaulted.
fn audit_envelope_columns() -> &'static [(&'static str, &'static str)] {
    &[
        ("actor", "CLOB NOT NULL"),
        ("actor_source", "CLOB"),
        ("client", "CLOB"),
        ("request_id", "CLOB"),
        ("reason", "CLOB"),
        ("prev_hash", "RAW(32)"),
        ("row_hash", "RAW(32)"),
        // SHA3-256 alongside SHA-256 (spec M3.16a): a second chain in a
        // different design family, so one line of cryptanalysis cannot take
        // both. `prev_hash_sha3` is the SHA-3 chain's own predecessor link;
        // the two chains are independent and verified independently.
        ("prev_hash_sha3", "RAW(32)"),
        ("row_hash_sha3", "RAW(32)"),
        // The keyed tag, `<key-id>:<hex>`, or NULL when unkeyed. The key id
        // travels with the tag so a verifier can distinguish "signed with a
        // key I do not hold" from "tampered with" — different claims that
        // must never be conflated — and so rotating a key does not invalidate
        // every historical row at once.
        ("row_mac", "CLOB"),
    ]
}

/// The disclosure log (PR12.5): one row per read, not per change.
///
/// A store that records only mutations cannot answer "who looked at this
/// patient", which is the question an audit actually starts with.
///
/// `rtype` and `id` are bounded rather than `TEXT` so the auditor's indexes
/// below need no prefix on them.
fn access_log_table(s: &str) -> String {
    // `GENERATED BY DEFAULT AS IDENTITY` is 12.1 and so inside the 12.2 floor;
    // it replaces MySQL's AUTO_INCREMENT. `BY DEFAULT` rather than `ALWAYS` so
    // a restore can reinsert its original sequence numbers -- an audit log
    // whose keys renumber on restore is not the same log.
    //
    // `SYSTIMESTAMP` is the server clock and returns a TIMESTAMP WITH TIME
    // ZONE, which Oracle converts to this column's plain TIMESTAMP by dropping
    // the offset after normalizing -- consistent with `M14.11`, where every
    // stored instant is UTC.
    idempotent(&format!(
        "CREATE TABLE \"{s}\".\"fhir_oracle_access_log\" (\n\
         \x20 \"seq\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n\
         \x20 \"ts\" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,\n\
         \x20 \"request_id\" CLOB,\n\
         \x20 \"actor\" CLOB NOT NULL,\n\
         \x20 \"actor_source\" CLOB,\n\
         \x20 \"client\" CLOB,\n\
         \x20 \"interaction\" VARCHAR2(64 CHAR) NOT NULL,\n\
         \x20 \"rtype\" VARCHAR2(64 CHAR),\n\
         \x20 \"id\" {ID_COL},\n\
         \x20 \"version_id\" NUMBER(19),\n\
         \x20 \"outcome\" VARCHAR2(64 CHAR) NOT NULL,\n\
         \x20 \"result_count\" NUMBER(19),\n\
         \x20 \"reason\" CLOB\n\
         )"
    ))
}

/// Counter-signatures over history rows, appended when a key is retired
/// (spec M3.16d).
///
/// A separate table rather than an update to `row_mac`, for two reasons.
/// History is append-only, and re-signing in place would be the application
/// doing exactly what the append-only guard exists to prevent. And the
/// original tag is evidence: replacing it destroys the record of what the
/// retired key attested, leaving no way to tell a legitimate re-signing from
/// a forged one.
///
/// The uniqueness constraint covers `row_mac`, which is unbounded `text` in the
/// PostgreSQL original; here it is bounded so the unique key fits in 3072
/// bytes. A MAC is `<key-id>:<hex>` and never approaches the limit.
fn countersign_table(s: &str) -> String {
    // `row_mac` is bounded here for the same reason as on MySQL -- it is in a
    // unique key -- though the Oracle limit is different (a key entry must fit
    // in about 3/4 of a block, not 3072 bytes). 191 characters is inherited
    // rather than derived; a MAC is `<key-id>:<hex>` and never approaches
    // either limit.
    //
    // No `COLLATE`: this database is AL32UTF8 with the default binary
    // collation, so comparison is already byte-exact (`M14.10`).
    idempotent(&format!(
        "CREATE TABLE \"{s}\".\"fhir_oracle_countersign\" (\n\
         \x20 \"seq\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n\
         \x20 \"rtype\" VARCHAR2(64 CHAR) NOT NULL,\n\
         \x20 \"id\" {ID_COL} NOT NULL,\n\
         \x20 \"version_id\" NUMBER(19) NOT NULL,\n\
         \x20 \"row_mac\" VARCHAR2(191 CHAR) NOT NULL,\n\
         \x20 \"signed_at\" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,\n\
         \x20 \"actor\" CLOB NOT NULL,\n\
         \x20 \"reason\" CLOB NOT NULL,\n\
         \x20 CONSTRAINT \"fhir_oracle_countersign_uq\" UNIQUE \
         (\"rtype\", \"id\", \"version_id\", \"row_mac\")\n\
         )"
    ))
}

fn access_log_indexes(s: &str) -> Vec<String> {
    // The three questions an auditor asks: what happened to this patient,
    // what did this person see, and what happened in this window.
    let t = "fhir_oracle_access_log";
    vec![
        idempotent(&format!(
            "CREATE INDEX \"{s}\".\"fhir_oracle_access_log_subject_ix\" \
             ON \"{s}\".\"{t}\" (\"rtype\", \"id\", \"ts\")"
        )),
        // No index on `actor`. MySQL indexes a 191-character prefix of it;
        // Oracle cannot index a CLOB at all (`ORA-02327`, measured), and there
        // is no prefix syntax to fall back on. Answering "what did this person
        // see" therefore needs the `U1` adjunct channel extended to this table,
        // which it is not yet -- `fhir_oracle_access_log` is not in the
        // relational map, so `U11`'s walk never reaches it (`M14.29`).
        idempotent(&format!(
            "CREATE INDEX \"{s}\".\"fhir_oracle_access_log_ts_ix\" \
             ON \"{s}\".\"{t}\" (\"ts\")"
        )),
    ]
}

/// History is append-only in the database, not merely by convention: an
/// application bug cannot rewrite it, and escaping this is a deliberate act
/// that leaves its own trace (M3.17).
///
/// **One trigger, not MySQL's two.** Oracle lets a single trigger name several
/// events and tell them apart with `UPDATING`/`DELETING`, and it has
/// `CREATE OR REPLACE TRIGGER`, so neither the pair nor the preceding
/// `DROP … IF EXISTS` that MySQL needs has any purpose here.
///
/// UPDATE is never permitted: there is no legitimate reason to rewrite a
/// history row in place. DELETE is permitted only during a declared erasure,
/// which is how `purge` performs a GDPR Art. 17 erasure (M3.18) and which
/// leaves a tombstone naming who did it. The guard is not a defence against the
/// application itself — the application can declare an erasure — but against
/// the far likelier accident of ordinary code, a migration, or a stray `DELETE`
/// touching history at all.
///
/// # How the erasure flag travels (`M14.29`)
///
/// MySQL reads a session variable, `@fhir_oracle_erasure`. Oracle has no such
/// thing. The alternatives are an application context — `CREATE CONTEXT` plus a
/// PL/SQL package that owns it — or `CLIENT_INFO`, a session-scoped string that
/// `DBMS_APPLICATION_INFO.SET_CLIENT_INFO` sets with **no privilege at all**.
///
/// `CLIENT_INFO` is chosen. An application context is the tidier design and is
/// what a from-scratch Oracle schema would use, but it makes installing this
/// port require `CREATE ANY CONTEXT`, and a port that cannot be installed
/// without a DBA is a port that gets installed as SYSTEM.
///
/// # The empty-string trap, found by executing it
///
/// The MySQL original reads `COALESCE(@fhir_oracle_erasure, '') <> 'on'`, and
/// the direct translation — `NVL(SYS_CONTEXT(…), '') != …` — **fails open**.
/// In Oracle the empty string *is* NULL, so `NVL(x, '')` is still NULL when the
/// context is unset, `NULL != 'fhir_oracle_erasure=on'` evaluates to NULL
/// rather than TRUE, and the `ELSIF` is not taken: the DELETE proceeds.
///
/// It was written that way, installed, and the guard let an ordinary DELETE
/// through with no error at all. Nothing about reading the trigger suggests it;
/// only running it does. Hence the sentinel is `'unset'` and not `''`, and
/// hence `T11.10`-style execution of a *guard* — proving it refuses, not merely
/// that it compiles — is mandatory for this port.
///
/// The cost is real and is stated rather than buried: `CLIENT_INFO` is a
/// general-purpose field that monitoring tools and connection pools also write,
/// so a pool that recycles a connection without clearing it could leave the
/// erasure declaration set for the next borrower. A store using this MUST set
/// it immediately before the delete and clear it immediately after, in the same
/// transaction, and MUST NOT rely on the pool. That is a weaker guarantee than
/// MySQL's session variable and is the reason this is a numbered departure and
/// not an implementation detail.
#[must_use]
pub fn append_only_triggers(s: &str, table: &str) -> Vec<String> {
    let trg = index_name(table, &["append_only_trg"]);
    vec![format!(
        "CREATE OR REPLACE TRIGGER \"{s}\".\"{trg}\"\n\
         BEFORE UPDATE OR DELETE ON \"{s}\".\"{table}\"\n\
         FOR EACH ROW\n\
         BEGIN\n\
         \x20 IF UPDATING THEN\n\
         \x20   raise_application_error(-20001, \
         'fhir-oracle: UPDATE forbidden; history is append-only (M3.17)');\n\
         \x20 ELSIF NVL(SYS_CONTEXT('USERENV', 'CLIENT_INFO'), 'unset') != \
         'fhir_oracle_erasure=on' THEN\n\
         \x20   raise_application_error(-20002, \
         'fhir-oracle: DELETE forbidden; history is append-only (M3.17)');\n\
         \x20 END IF;\n\
         END;"
    )]
}

/// One index per distinct search-target column set (P6.4).
///
/// Oracle has no prefix-index syntax and cannot index a `CLOB` at all
/// (`ORA-02327`, measured on 26ai). Where MySQL indexes `col(255)`, this port
/// indexes the **bounded adjunct** instead — `<col>_idx`, materialized by
/// `U1`–`U10` precisely so that this is possible. A target whose column is a
/// CLOB with no adjunct is skipped rather than emitted: an index statement that
/// cannot execute would abort the install, and one silently dropped would leave
/// `P6.4` unmet without saying so, so the skip is counted and reported by
/// `search_index_gaps`.
pub fn search_indexes(schema: &str, rm: &ResourceMap) -> Vec<String> {
    use crate::model::TargetKind;
    let mut seen = std::collections::BTreeSet::new();
    let mut out = Vec::new();
    for def in &rm.search {
        for t in &def.targets {
            let cols: Vec<&str> = match &t.kind {
                // Index the folded column when there is one: it is what every
                // modifier except `:exact` actually compares.
                TargetKind::Str { col, norm } => vec![norm.as_deref().unwrap_or(col)],
                TargetKind::Number { col } | TargetKind::Uri { col } => {
                    vec![col]
                }
                TargetKind::Token { system, code } => match system {
                    Some(s) => vec![s, code],
                    None => vec![code],
                },
                TargetKind::Date { lo, hi } => match hi {
                    Some(h) => vec![lo, h],
                    None => vec![lo],
                },
                TargetKind::Quantity { value, .. } => vec![value],
                TargetKind::Reference { c_type, c_id, .. } => vec![c_type, c_id],
            };
            let table = &rm.tables[t.table as usize];
            let key = format!("{}:{}", table.name, cols.join(","));
            if !seen.insert(key) {
                continue;
            }
            let Some(collist) = index_columns(table, &cols) else {
                continue;
            };
            let name = index_name(&table.name, &cols);
            out.push(format!(
                "CREATE INDEX \"{schema}\".\"{name}\" ON \"{schema}\".\"{}\" ({})",
                table.name,
                collist.join(", ")
            ));
        }
    }
    out
}

/// Render an index's column list, substituting the bounded adjunct for any
/// column Oracle cannot index.
///
/// Prefers the **bounded** adjunct, and falls back to the **digest**.
///
/// That order follows `U2a`, which attaches adjuncts by the operation the
/// search performs. A `string` or `uri` target is matched by prefix as well as
/// by equality, so it carries `<col>_idx` and that is what an index must cover.
/// A `token` or `reference` target is only ever compared for equality, so `U2a`
/// gives it `<col>_h` alone — and an index on the digest serves that exactly,
/// with `U6`'s confirming comparison resolving the collision case.
///
/// Taking only the bounded column would have declared 1,231 of R5's 1,947
/// search targets unindexable, when in fact nearly all of them are token and
/// reference targets whose digest is the right index. That was the first
/// version of this function, and the count is what exposed it.
///
/// Returns `None` when some column of the key is unindexable and has neither
/// adjunct: a partial key would silently answer a different question than the
/// one `P6.4` asked for.
fn index_columns(table: &Table, cols: &[&str]) -> Option<Vec<String>> {
    let ty_of = |name: &str| table.cols.iter().find(|c| c.name == name).map(|c| c.ty);
    cols.iter()
        .map(|c| match ty_of(c) {
            // A column the map does not describe is a system column, always
            // bounded, and indexable as itself.
            None => Some(format!("\"{c}\"")),
            Some(ty) if !needs_adjunct(ty) => Some(format!("\"{c}\"")),
            Some(_) => table
                .adjunct_cols
                .iter()
                .find(|a| a.source == **c)
                .and_then(|a| a.bounded.as_ref().or(a.digest.as_ref()))
                .map(|b| format!("\"{b}\"")),
        })
        .collect()
}

/// The search targets `search_indexes` could not index, and why.
///
/// `P6.4` is not satisfiable for these until each one's column gains a bounded
/// adjunct, and a port that emits a schema without them MUST NOT claim it. This
/// exists so the gap is enumerable rather than inferred from a missing index —
/// counting what was skipped is the difference between a known limit and a
/// silent one (`T11.12`).
#[must_use]
pub fn search_index_gaps(rm: &ResourceMap) -> Vec<String> {
    use crate::model::TargetKind;
    let mut seen = std::collections::BTreeSet::new();
    let mut out = Vec::new();
    for def in &rm.search {
        for t in &def.targets {
            let cols: Vec<&str> = match &t.kind {
                TargetKind::Str { col, norm } => vec![norm.as_deref().unwrap_or(col)],
                TargetKind::Number { col } | TargetKind::Uri { col } => vec![col],
                TargetKind::Token { system, code } => match system {
                    Some(s) => vec![s, code],
                    None => vec![code],
                },
                TargetKind::Date { lo, hi } => match hi {
                    Some(h) => vec![lo, h],
                    None => vec![lo],
                },
                TargetKind::Quantity { value, .. } => vec![value],
                TargetKind::Reference { c_type, c_id, .. } => vec![c_type, c_id],
            };
            let table = &rm.tables[t.table as usize];
            let key = format!("{}:{}", table.name, cols.join(","));
            if !seen.insert(key.clone()) {
                continue;
            }
            if index_columns(table, &cols).is_none() {
                out.push(key);
            }
        }
    }
    out
}

fn index_name(table: &str, cols: &[&str]) -> String {
    let full = format!("{table}_{}_ix", cols.join("_"));
    if full.len() <= 63 {
        return full;
    }
    // FNV-1a of the full name keeps truncated names unique and stable.
    let mut h: u64 = 0xcbf29ce484222325;
    for b in full.as_bytes() {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x100000001b3);
    }
    let hex = format!("{h:016x}");
    let keep: String = full.chars().take(63 - 17).collect();
    format!("{keep}_{hex}")
}

/// One `CREATE TABLE`. Indexes are **not** included: Oracle has no inline index
/// clause, so `ddl_in` emits them separately (`M14.30`).
/// `path`'s type on the ext and deep tables: bounded when the asset
/// records `U12a`'s `path_bound` (`M14.38`), the legacy `CLOB` for a
/// pre-`U12a` asset — the emitted schema follows the asset it was handed
/// (`G2.2`). `VARCHAR2`, never `CHAR`: the values vary in length, which
/// is where PAD SPACE would bite (`M3.6b`).
fn path_type(rm: &ResourceMap) -> String {
    if rm.path_bound > 0 {
        format!("VARCHAR2({} CHAR)", rm.path_bound)
    } else {
        "CLOB".to_string()
    }
}

pub fn create_table(schema: &str, rm: &ResourceMap, t: &Table) -> String {
    let base = &rm.base_table().name;
    let path_ty = path_type(rm);
    let mut sql = format!("CREATE TABLE \"{schema}\".\"{}\" (\n", t.name);
    match t.kind {
        TableKind::Base => {
            let _ = writeln!(sql, "  \"id\" {ID_COL} NOT NULL PRIMARY KEY,");
            sql.push_str("  \"version_id\" NUMBER(19) NOT NULL,\n");
            sql.push_str("  \"last_updated\" TIMESTAMP(6) NOT NULL");
            push_data_cols(&mut sql, t);
        }
        TableKind::Elem => {
            // `ords` is the array path, stored as the same text image the
            // PostgreSQL original wrote (M14.9). RAW keeps it one byte per
            // character against the key budget and compares exactly, and
            // unlike a CLOB it can be part of a primary key at all.
            let _ = write!(
                sql,
                "  \"rid\" {ID_COL} NOT NULL,\n  \"ords\" RAW(255) NOT NULL"
            );
            push_data_cols(&mut sql, t);
            let _ = write!(
                sql,
                ",\n  PRIMARY KEY (\"rid\", \"ords\"),\n\
                 \x20 CONSTRAINT \"{}\" FOREIGN KEY (\"rid\") REFERENCES \"{schema}\".\"{base}\" (\"id\") ON DELETE CASCADE",
                fk_name(&t.name)
            );
        }
        TableKind::Ext => {
            // The natural key — (rid, path, ords, modifier, ext_ord, leaf) —
            // includes two CLOB columns, which Oracle will not admit to a key
            // at all (`ORA-02329`). There is no prefix syntax to fall back on,
            // and a prefix would not do anyway: it cannot enforce uniqueness
            // over the full value, so two rows differing only past the prefix
            // would collide and silently lose data. Hence a hash surrogate
            // (M14.12), computed in Rust over the canonically joined natural
            // key.
            let _ = write!(
                sql,
                "  \"key_hash\" RAW(32) NOT NULL PRIMARY KEY,\n\
                 \x20 \"rid\" {ID_COL} NOT NULL,\n\
                 \x20 \"path\" {path_ty} NOT NULL,\n\
                 \x20 \"ords\" RAW(255) NOT NULL,\n\
                 \x20 \"modifier\" NUMBER(1) NOT NULL,\n\
                 \x20 \"ext_ord\" NUMBER(5) NOT NULL,\n\
                 \x20 \"url\" CLOB,\n\
                 \x20 \"leaf\" CLOB NOT NULL,\n\
                 \x20 \"v_kind\" CHAR(1 CHAR) NOT NULL,\n\
                 \x20 \"v_text\" CLOB,\n\
                 \x20 \"v_num\" CLOB,\n\
                 \x20 \"v_bool\" NUMBER(1)",
            );
            push_adjunct_cols(&mut sql, t);
            push_bool_checks(&mut sql, &t.name, &["modifier", "v_bool"]);
            let _ = write!(
                sql,
                ",\n  CONSTRAINT \"{}\" FOREIGN KEY (\"rid\") REFERENCES \"{schema}\".\"{base}\" (\"id\") ON DELETE CASCADE",
                fk_name(&t.name)
            );
        }
        TableKind::Deep => {
            let _ = write!(
                sql,
                "  \"key_hash\" RAW(32) NOT NULL PRIMARY KEY,\n\
                 \x20 \"rid\" {ID_COL} NOT NULL,\n\
                 \x20 \"path\" {path_ty} NOT NULL,\n\
                 \x20 \"ords\" RAW(255) NOT NULL,\n\
                 \x20 \"leaf\" CLOB NOT NULL,\n\
                 \x20 \"v_kind\" CHAR(1 CHAR) NOT NULL,\n\
                 \x20 \"v_text\" CLOB,\n\
                 \x20 \"v_num\" CLOB,\n\
                 \x20 \"v_bool\" NUMBER(1)",
            );
            push_adjunct_cols(&mut sql, t);
            push_bool_checks(&mut sql, &t.name, &["v_bool"]);
            let _ = write!(
                sql,
                ",\n  CONSTRAINT \"{}\" FOREIGN KEY (\"rid\") REFERENCES \"{schema}\".\"{base}\" (\"id\") ON DELETE CASCADE",
                fk_name(&t.name)
            );
        }
        TableKind::Contained => {
            let _ = write!(
                sql,
                "  \"rid\" {ID_COL} NOT NULL,\n\
                 \x20 \"ord\" NUMBER(5) NOT NULL,\n\
                 \x20 \"resource\" CLOB NOT NULL,\n\
                 \x20 PRIMARY KEY (\"rid\", \"ord\"),\n\
                 \x20 CONSTRAINT \"{}\" FOREIGN KEY (\"rid\") REFERENCES \"{schema}\".\"{base}\" (\"id\") ON DELETE CASCADE",
                fk_name(&t.name)
            );
        }
        TableKind::History => {
            // The audit envelope (M3.15) and the hash chain (M3.16) live on
            // the same row as the change they describe, written by the same
            // statement inside the same transaction: an audit record that can
            // be lost independently of its change is not an audit record.
            let _ = write!(
                sql,
                "  \"id\" {ID_COL} NOT NULL,\n\
                 \x20 \"version_id\" NUMBER(19) NOT NULL,\n\
                 \x20 \"last_updated\" TIMESTAMP(6) NOT NULL,\n\
                 \x20 \"op\" CHAR(1 CHAR) NOT NULL,\n\
                 \x20 \"resource\" CLOB"
            );
            for (name, ty) in audit_envelope_columns() {
                let _ = write!(sql, ",\n  \"{name}\" {ty}");
            }
            sql.push_str(",\n  PRIMARY KEY (\"id\", \"version_id\")");
        }
    }
    sql.push_str("\n)");
    sql
}

/// The `CHECK (col IN (0,1))` that makes a `NUMBER(1)` a boolean.
///
/// `col_sql` cannot emit this: a column-level check may not name another
/// column, so `NUMBER(1) CHECK (VALUE IN (0,1))` fails at `CREATE TABLE` with
/// `ORA-02438` — found by executing it (`M14.23e`). Only `create_table` knows
/// the column's name, so the constraint is written here, at table level, and
/// this is what lets the port claim `M14.8`.
///
/// The named columns are the fixed-shape ones; `push_data_cols` handles
/// map-driven `Bool` columns itself. A column absent from the table is skipped
/// rather than asserted, because `Deep` has no `modifier`.
fn push_bool_checks(sql: &mut String, table: &str, cols: &[&str]) {
    for c in cols {
        let _ = write!(
            sql,
            ",\n  CONSTRAINT \"{}\" CHECK (\"{c}\" IN (0, 1))",
            index_name(table, &[c, "bool"])
        );
    }
}

/// Foreign-key constraint names share a namespace across the whole schema in
/// MySQL, not just the table, so they get the same 63-byte fitting as indexes.
fn fk_name(table: &str) -> String {
    index_name(table, &["rid_fk"])
}

/// The `rid` lookup index on `Ext`/`Deep`, which the read path uses since those
/// tables no longer key on `rid` first.
fn rid_index_name(table: &str) -> String {
    index_name(table, &["rid"])
}

/// Emit the `U1` adjuncts a fixed-shape table carries.
///
/// `Ext` and `Deep` hardcode their data columns, so `push_data_cols` never sees
/// them, and the adjunct columns the generator attached to `url`, `leaf` and
/// `v_text` would never reach the schema — leaving the map describing columns
/// the database does not have (**F-46**).
///
/// This writes nothing on a dialect that indexes its unbounded text type,
/// because `add_adjunct_columns` attached nothing there (`U9`). It must be
/// called *before* the trailing key and constraint clauses: SQLite requires
/// every column definition to precede them.
fn push_adjunct_cols(sql: &mut String, t: &Table) {
    for a in &t.adjunct_cols {
        if let Some(n) = &a.bounded {
            let _ = write!(sql, ",\n  \"{n}\" {}", col_sql(ColTy::TextIdx));
        }
        if let Some(n) = &a.digest {
            let _ = write!(sql, ",\n  \"{n}\" {}", col_sql(ColTy::Digest));
        }
    }
}

fn push_data_cols(sql: &mut String, t: &Table) {
    for c in &t.cols {
        let _ = write!(sql, ",\n  \"{}\" {}", c.name, col_sql(c.ty));
    }
    // The boolean constraint `col_sql` could not write, for the map-driven
    // columns (`M14.23e`). Table-level, because a column check may not name a
    // column.
    let bools: Vec<&str> = t
        .cols
        .iter()
        .filter(|c| c.ty == ColTy::Bool)
        .map(|c| c.name.as_str())
        .collect();
    push_bool_checks(sql, &t.name, &bools);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(name: &str, ty: ColTy) -> crate::model::Column {
        crate::model::Column {
            name: name.to_string(),
            ty,
            path: String::new(),
        }
    }

    fn table(name: &str, cols: Vec<crate::model::Column>) -> Table {
        Table {
            name: name.to_string(),
            kind: TableKind::Elem,
            path: String::new(),
            cols,
            norm_cols: Vec::new(),
            adjunct_cols: Vec::new(),
        }
    }

    /// These replace eleven `#[ignore]`d tests that asserted MySQL behaviour
    /// (`M14.25`, **F-08**). They are kept as a set because each one names a
    /// MySQL construct that must **not** reappear: this file was produced by
    /// substitution, and substitution is how it went wrong the first time.
    #[test]
    fn no_mysql_or_postgres_constructs_survive() {
        let mut sql = String::new();
        sql.push_str(&schema_wide_objects("r5").join("\n"));
        sql.push_str(&append_only_triggers("r5", "patient_history").join("\n"));
        for ty in [
            ColTy::Bool,
            ColTy::Int,
            ColTy::BigInt,
            ColTy::Numeric,
            ColTy::Text,
            ColTy::TextC,
            ColTy::TextIdx,
            ColTy::Digest,
            ColTy::Date,
            ColTy::Timestamptz,
            ColTy::Jsonb,
        ] {
            sql.push(' ');
            sql.push_str(col_sql(ty));
        }
        for bad in [
            "AUTO_INCREMENT",
            "ENGINE=InnoDB",
            "utf8mb4",
            "TINYINT",
            "DATETIME",
            "LONGTEXT",
            "MEDIUMTEXT",
            "VARBINARY",
            "SIGNAL SQLSTATE",
            "IF NOT EXISTS",
            "DROP TRIGGER",
            "`",     // MySQL quoting
            "jsonb", // PostgreSQL
            "bytea",
            "plpgsql",
            "unaccent",
        ] {
            assert!(
                !sql.contains(bad),
                "emitted DDL still contains the non-Oracle construct {bad:?}"
            );
        }
    }

    #[test]
    fn identifiers_are_double_quoted_not_backquoted() {
        // Not cosmetic: an unquoted Oracle identifier folds to upper case, and
        // every name this generator produces is lower case. Emitting them bare
        // would create PATIENT and then fail to find "patient".
        let sql = access_log_table("r5");
        assert!(sql.contains("\"fhir_oracle_access_log\""));
        assert!(!sql.contains('`'));
    }

    #[test]
    fn decimal_does_not_become_a_fixed_scale_number() {
        // M3.6a/M14.7: Oracle's NUMBER normalizes 1.50 to 1.5, which loses the
        // textual precision R4.2 requires to survive round-trip.
        let sql = col_sql(ColTy::Numeric);
        assert!(sql.starts_with("VARCHAR2"), "Numeric bound to {sql}");
        assert!(!sql.contains("NUMBER"));
    }

    #[test]
    fn json_is_stored_as_clob_to_preserve_signed_bytes() {
        // M3.6c/M14.12: Oracle's JSON type re-normalizes, so the bytes read
        // back would not be the bytes the hash chain signed.
        assert_eq!(col_sql(ColTy::Jsonb), "CLOB");
    }

    /// The guard that failed open (`M14.29a`). This asserts the *shape* only —
    /// that the sentinel is not the empty string — because a unit test cannot
    /// evaluate Oracle's NULL semantics. The behaviour is verified by executing
    /// a forbidden DELETE against a live database, and MUST be re-verified that
    /// way after any change here.
    #[test]
    fn the_erasure_sentinel_is_not_the_empty_string() {
        let trg = append_only_triggers("r5", "patient_history").join("\n");
        assert!(
            trg.contains("NVL(SYS_CONTEXT('USERENV', 'CLIENT_INFO'), 'unset')"),
            "the sentinel must be non-empty: Oracle treats '' as NULL, so \
             NVL(x, '') != 'y' is NULL rather than TRUE and the guard never \
             fires. See M14.29a.\n{trg}"
        );
        assert!(
            !trg.contains("), '')"),
            "empty-string sentinel reintroduced"
        );
    }

    #[test]
    fn one_trigger_covers_both_events() {
        // Oracle allows several events on one trigger and has CREATE OR
        // REPLACE, so MySQL's two-triggers-plus-DROP pattern has no purpose.
        let trg = append_only_triggers("r5", "patient_history");
        assert_eq!(trg.len(), 1, "expected one trigger, got {}", trg.len());
        assert!(trg[0].contains("BEFORE UPDATE OR DELETE"));
        assert!(trg[0].contains("CREATE OR REPLACE TRIGGER"));
        assert!(trg[0].contains("raise_application_error"));
    }

    #[test]
    fn idempotent_wrapper_swallows_only_name_clashes() {
        // Swallowing OTHERS would turn a syntax error into a silent success,
        // which is the failure this port is being audited for (M14.31).
        let w = idempotent("CREATE TABLE \"x\" (\"a\" NUMBER)");
        assert!(w.contains("SQLCODE NOT IN (-955, -1408)"));
        assert!(w.contains("THEN RAISE"));
        assert!(!w.contains("WHEN OTHERS THEN NULL"));
    }

    #[test]
    fn non_adjunct_columns_are_indexed_directly() {
        let t = table("t", vec![col("d", ColTy::Date), col("n", ColTy::Int)]);
        assert_eq!(
            index_columns(&t, &["d", "n"]),
            Some(vec!["\"d\"".to_string(), "\"n\"".to_string()])
        );
    }

    #[test]
    fn system_columns_absent_from_the_map_are_indexed_directly() {
        // `rid`/`ords` are not in `Table::cols`; they are bounded by
        // construction and indexable as themselves.
        let t = table("t", vec![col("a", ColTy::TextC)]);
        assert_eq!(
            index_columns(&t, &["rid", "a"]),
            Some(vec!["\"rid\"".to_string(), "\"a\"".to_string()])
        );
    }

    /// A CLOB with no adjunct cannot be indexed and MUST yield no index at all
    /// — not a partial key, which would answer a different question (`M14.32`).
    #[test]
    fn an_unindexable_column_without_an_adjunct_yields_no_index() {
        let t = table("t", vec![col("a", ColTy::Text)]);
        assert_eq!(index_columns(&t, &["a"]), None);
    }

    /// `U2a`: bounded is preferred, digest is the fallback, and a digest alone
    /// is enough — which is what token and reference targets carry.
    #[test]
    fn the_bounded_adjunct_is_preferred_and_the_digest_is_the_fallback() {
        use crate::model::Adjuncts;
        let mut t = table("t", vec![col("a", ColTy::Text), col("b", ColTy::Text)]);
        t.adjunct_cols = vec![
            Adjuncts {
                source: "a".into(),
                bounded: Some("a_idx".into()),
                digest: Some("a_h".into()),
            },
            Adjuncts {
                source: "b".into(),
                bounded: None,
                digest: Some("b_h".into()),
            },
        ];
        assert_eq!(
            index_columns(&t, &["a", "b"]),
            Some(vec!["\"a_idx\"".to_string(), "\"b_h\"".to_string()])
        );
    }

    /// `M14.8` rests on this. `col_sql` cannot carry the CHECK (`ORA-02438`,
    /// `M14.23e`), so if `create_table` does not write it, a `Bool` column is an
    /// unconstrained `NUMBER(1)` that accepts 2 — and the port would be
    /// claiming a boolean it does not have.
    ///
    /// Verified against a live 26ai as well: inserting `modifier = 2` is
    /// refused with `ORA-02290`. This test is what keeps that true.
    #[test]
    fn bool_columns_get_a_table_level_check() {
        use crate::model::ResourceMap;
        let rm = ResourceMap {
            name: "T".into(),
            tables: vec![Table {
                name: "t_ext".into(),
                kind: TableKind::Ext,
                path: String::new(),
                cols: Vec::new(),
                norm_cols: Vec::new(),
                adjunct_cols: Vec::new(),
            }],
            nodes: Vec::new(),
            root: 0,
            search: Vec::new(),
            path_bound: 0,
        };
        let sql = create_table("r5", &rm, &rm.tables[0]);
        for c in ["modifier", "v_bool"] {
            assert!(
                sql.contains(&format!("CHECK (\"{c}\" IN (0, 1))")),
                "no boolean CHECK on {c}; an unconstrained NUMBER(1) accepts 2\n{sql}"
            );
        }
        // And it must be table-level, not inside the type.
        assert!(!sql.contains("NUMBER(1) CHECK"), "ORA-02438: see M14.23e");
    }

    /// `M14.38`/`U12a`: an asset that records `path_bound` gets a bounded,
    /// comparable `path`; a pre-`U12a` asset (bound 0) keeps the legacy
    /// `CLOB`, so reinstalling an old asset reproduces the old schema
    /// (`G2.2`). `VARCHAR2`, never `CHAR` — the values vary in length,
    /// which is where PAD SPACE bites (`M3.6b`).
    #[test]
    fn a_recorded_path_bound_narrows_path_and_a_legacy_asset_keeps_clob() {
        use crate::model::ResourceMap;
        let mut rm = ResourceMap {
            name: "T".into(),
            tables: vec![Table {
                name: "t_ext".into(),
                kind: TableKind::Ext,
                path: String::new(),
                cols: Vec::new(),
                norm_cols: Vec::new(),
                adjunct_cols: Vec::new(),
            }],
            nodes: Vec::new(),
            root: 0,
            search: Vec::new(),
            path_bound: 192,
        };
        let sql = create_table("r5", &rm, &rm.tables[0]);
        assert!(
            sql.contains("\"path\" VARCHAR2(192 CHAR) NOT NULL"),
            "recorded bound not applied:\n{sql}"
        );
        assert!(!sql.contains("\"path\" CLOB"));

        rm.path_bound = 0;
        let sql = create_table("r5", &rm, &rm.tables[0]);
        assert!(
            sql.contains("\"path\" CLOB NOT NULL"),
            "legacy asset must keep CLOB:\n{sql}"
        );
    }

    #[test]
    fn schema_wide_objects_no_longer_emit_a_norm_function() {
        // The PostgreSQL original emitted `fhir_*_norm` and never called it.
        // Folding is pure Rust, so the port carries neither the function nor
        // its `unaccent` extension dependency.
        let all = schema_wide_objects("r5").join("\n");
        assert!(!all.contains("CREATE FUNCTION"));
        assert!(!all.contains("_norm"));
        assert!(!all.contains("unaccent"));
        assert!(!all.contains("plpgsql"));
    }
}

#[cfg(test)]
mod oracle_bounds {
    use super::*;

    /// Every `VARCHAR2` bound this emitter declares must fit the measured
    /// ceiling, in **bytes** — the trap `M14.23d` records, where a `CHAR`
    /// bound reads as characters and is enforced as bytes.
    ///
    /// Mutation-verified (`T11.10`): widening `TextC` to `VARCHAR2(1001 CHAR)`
    /// fails this, which is the point — 1001 × 4 exceeds 4000 and Oracle would
    /// refuse the `CREATE TABLE` with `ORA-00910`.
    #[test]
    fn declared_varchar2_bounds_fit_the_measured_ceiling() {
        for ty in [ColTy::Numeric, ColTy::TextC, ColTy::TextIdx] {
            let sql = col_sql(ty);
            let Some(rest) = sql.strip_prefix("VARCHAR2(") else {
                continue;
            };
            let chars: usize = rest
                .split_whitespace()
                .next()
                .expect("a bound")
                .parse()
                .expect("numeric bound");
            assert!(
                chars <= MAX_VARCHAR2_CHARS,
                "{ty:?} declares VARCHAR2({chars} CHAR) = {} bytes, over the \
                 measured {MAX_VARCHAR2_BYTES}-byte ceiling",
                chars * BYTES_PER_CHAR
            );
        }
    }

    /// `Text` must not be bounded at all: a FHIR string has no length bound,
    /// and binding it to `VARCHAR2` would refuse long values with `ORA-12899`
    /// rather than store them, which `R4.2` forbids.
    #[test]
    fn unbounded_text_is_a_clob() {
        assert_eq!(col_sql(ColTy::Text), "CLOB");
        assert_eq!(col_sql(ColTy::Jsonb), "CLOB");
    }

    /// `M14.23e`: the CHECK cannot be in the type string, so it must not be.
    #[test]
    fn bool_carries_no_inline_check() {
        let sql = col_sql(ColTy::Bool);
        assert_eq!(sql, "NUMBER(1)");
        assert!(
            !sql.contains("CHECK"),
            "an inline CHECK fails with ORA-02438; create_table owns it"
        );
    }
}
