//! `O10.7` against a live server: TLS is configurable, and verification
//! actually verifies.
//!
//! # Why the third test is the one that matters
//!
//! Proving that a verifying connection *succeeds* proves almost nothing: if
//! certificate checking were a no-op, it would succeed too. So the
//! load-bearing assertion here is that `TrustServerCertificate=false`
//! (`tiberius`'s verifying `TrustConfig::Default`, using the OS's native
//! root store) **rejects** a connection to `azure-sql-edge`'s self-signed
//! certificate, which `TrustServerCertificate=true` (`TrustConfig::TrustAll`)
//! accepts without complaint.
//!
//! A green run of tests 1 and 2 with test 3 removed would be consistent with
//! a build where certificate checking silently never engages.
//!
//! # What the rejection actually is, found by running it with `RUST_LOG=trace`
//!
//! It is not the "unknown issuer" a chain-trust failure usually reads as.
//! `azure-sql-edge` presents a certificate whose subject is literally
//! `CN=SSL_Self_Signed_Fallback`, and `rustls-webpki` refuses to parse it at
//! all: `invalid peer certificate: Other(UnsupportedCertVersion)`. That is a
//! *stricter* rejection than an ordinary untrusted-chain error, not a
//! weaker one — the certificate fails structural validation before chain
//! trust is ever evaluated — and it is deterministic across repeated
//! connections, not a fluke.
//!
//! Needs `FHIR_MSSQL_TEST_DSN`; `scripts/db.sh up` prints it. Skips silently
//! without one, matching the rest of this port's live suite's convention.

use std::sync::Arc;

use fhir_mssql_map::model::RelMap;
use fhir_mssql_store::mssql::MsSqlStore;

mod common;

fn dsn() -> Option<String> {
    common::dsn().map(str::to_string)
}

/// Rebuild an ADO connection string with some keys added or replaced.
///
/// Simpler than a real parser: this port's DSNs are always `key=value`
/// pairs joined by `;`, generated by `scripts/db.sh`'s `dsn_line`, never
/// hand-typed by a user of this test.
fn with_params(base: &str, overrides: &[(&str, &str)]) -> String {
    let mut pairs: Vec<(String, String)> = base
        .split(';')
        .filter_map(|kv| kv.split_once('='))
        .map(|(k, v)| (k.to_ascii_lowercase(), v.to_string()))
        .collect();
    for (k, v) in overrides {
        let k = k.to_ascii_lowercase();
        if let Some(existing) = pairs.iter_mut().find(|(ek, _)| *ek == k) {
            existing.1 = (*v).to_string();
        } else {
            pairs.push((k, (*v).to_string()));
        }
    }
    pairs
        .into_iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect::<Vec<_>>()
        .join(";")
}

fn map() -> Arc<RelMap> {
    Arc::new(RelMap {
        fhir_version: "5.0.0".into(),
        schema: "fhir_mssql_ssltest".into(),
        resources: Default::default(),
    })
}

#[tokio::test]
async fn tls_is_configurable_and_verification_is_not_a_no_op() {
    let Some(base) = dsn() else {
        eprintln!("skipping: set FHIR_MSSQL_TEST_DSN to run");
        return;
    };

    // 1. The server is reachable at all, over `tiberius`'s default
    //    `EncryptionLevel::Off` (login-only encryption — see `mssql.rs`'s
    //    module doc and `M14.34`). Without this, test 3's failure could just
    //    be "no server".
    MsSqlStore::connect(&base, map())
        .await
        .expect("default encryption: the server must be reachable for this test to mean anything");

    // 2. Full-session TLS engages. This also proves the `rustls` feature is
    //    compiled into `tiberius` — with `default-features = false` and no
    //    `rustls` feature, there would be no TLS at all and this would fail
    //    to compile, let alone connect.
    let encrypt_trust_all = with_params(
        &base,
        &[("encrypt", "true"), ("TrustServerCertificate", "true")],
    );
    MsSqlStore::connect(&encrypt_trust_all, map())
        .await
        .expect("encrypt=true, TrustServerCertificate=true: the server offers TLS and the driver must use it");

    // 3. **Verification rejects a certificate that does not check out.**
    //
    // The error `bb8` surfaces here is its own "Timed out in bb8" — `pool::
    // connect_pool`'s eager reachability probe (added for a different reason,
    // see its own doc comment) retries through `bb8`'s connection timeout
    // before giving up, rather than propagating `tiberius`'s immediate
    // `invalid peer certificate: Other(UnsupportedCertVersion)` — confirmed
    // by running this same DSN directly against `tiberius::Client::connect`
    // outside the pool, bypassing `bb8` entirely. So this assertion checks
    // only that the connection **fails**, not the wrapped message text: the
    // message a caller sees depends on `bb8`'s retry/timeout behaviour, not
    // on whether the certificate was rejected, and asserting a specific
    // substring here would make the test fragile to a `bb8` version bump
    // rather than meaningful about `O10.7`.
    let encrypt_verify = with_params(
        &base,
        &[("encrypt", "true"), ("TrustServerCertificate", "false")],
    );
    let verified = MsSqlStore::connect(&encrypt_verify, map()).await;
    assert!(
        verified.is_err(),
        "TrustServerCertificate=false accepted azure-sql-edge's self-signed \
         certificate. Either certificate checking is a no-op — in which case \
         the O10.7 default is decorative — or this server has been given a \
         certificate that genuinely validates for this hostname, in which case \
         this test needs rewriting rather than deleting."
    );
}
